package com.formulamanager.sokker.acciones.sete;

import java.io.IOException;
import java.net.MalformedURLException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;

import javax.security.auth.login.LoginException;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.formulamanager.sokker.auxiliares.JSONUtil;
import com.formulamanager.sokker.auxiliares.Navegador;
import com.formulamanager.sokker.auxiliares.Util;
import com.formulamanager.sokker.bo.AsistenteBO;
import com.gargoylesoftware.htmlunit.FailingHttpStatusCodeException;
import com.gargoylesoftware.htmlunit.WebClient;
import com.gargoylesoftware.htmlunit.html.HtmlAnchor;
import com.gargoylesoftware.htmlunit.html.HtmlPage;
import com.jayway.jsonpath.JsonPath;

/**
 * Servlet implementation class Main
 */
@WebServlet("/sete")
public class SETE extends HttpServlet {
	private static final long serialVersionUID = 1L;
       
    /**
     * @see HttpServlet#HttpServlet()
     */
    public SETE() {
        super();
    }

	/**
	 * @see HttpServlet#doGet(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		if (request.getSession().getAttribute("tacticas") == null) {
			// Tácticas predefinidas
			List<Object[]> tacticas = dev_tacticas_predefinidas();
			request.getSession().setAttribute("tacticas", tacticas);
		}
		request.getRequestDispatcher("jsp/sete/sete.jsp").forward(request, response);
	}

    protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		try {
			// Tácticas predefinidas
//			List<Object[]> tacticas = dev_tacticas_predefinidas();
			List<Object[]> tacticas = new ArrayList<>();
			request.getSession().setAttribute("tacticas", tacticas);

			if (!Util.getBoolean(request, "confirmed")) {
				throw new RuntimeException("Login not confirmed");
			} else {
				String ilogin = request.getParameter("ilogin");
				String ipassword = request.getParameter("ipassword");

				new Navegador(false, ilogin, ipassword, request) {
					@Override
					protected void execute(WebClient navegador) throws FailingHttpStatusCodeException, MalformedURLException, IOException, LoginException, ParseException {
						//----------
						// TÁCTICAS
						//----------
						tacticas.addAll(get_tacticas(navegador, null));

						//----------------
						// Seleccionador?
						//----------------
						Integer tid_nt = obtener_tid_NT(navegador);
						if (tid_nt != null) {
							tacticas.add(null);
							tacticas.addAll(get_tacticas(navegador, tid_nt));
						}
						
						request.getSession().setAttribute("login", ilogin);
					}
				};

				request.getRequestDispatcher("jsp/sete/sete.jsp").forward(request, response);
			}
		} catch (FailingHttpStatusCodeException | LoginException | IOException | ParseException e) {
			e.printStackTrace();
			response.sendRedirect(request.getContextPath() + "/sete?error=" + e.getMessage());
		}
	}

	private List<Object[]> dev_tacticas_predefinidas() {
		List<Object[]> tacticas = new ArrayList<Object[]>();
		
		tacticas.add(new Object[] {"1", "Normal", "ADBCBEBDBECCCDDECECGDDDDDEEDFEFCFCEDECFEFCGCGDHCGEICICICIDHEJBJCJCICIDAFAFAGAHAHBEBGAGAGAHBGBGBGCGCGCECFCGDGDHDDDEDFEHEIEEEFEFFFFGHFHFHFIGIGAHAHAIAJAJAHAIAIBIBKCICICIBIBIDHDIDICJCKEGEHEIDKDLFIFJFJEJEKIIIIIIHJHJBKBLBKBMALCICKDKCLCMFKELDLDLDLFKEMELFMFMGKHMGLGMFMHKILIMIMIMILIMJMJMJNGBFCEDEEEFHBGBGAFBFEKBJAIBJBIDLAKAKBKCKCMALALBMCMENANBMBNDMDOANBODOEOFBDBFAHBIBICDCECGCIDJFCFEFGFHFIHDGEGFGHHIHDHEHFIHIIJDJEJFJHJILDLELFLGMHBGBGBHBJBLDFCGCICKCLFGFHFIFKFMHGGHGJGKHLIGIHIIHKHLJGJHJJJKJLMHLILJLKLLEJEKELFMGNFKFNGMGNHNILJNHMJOKNKMKMLOKOLOMKMMMOLOMOMLNLMONNNOOJOKOMNNOOEEEFEHEJEKGDGEGFGKGLJEIFJGIJJKKEJDKGJLKKLEKFLGKJLKNFNGMGNINJNENFNHNJNKHFHGHHHIHJIFIGIJIIIJKFKGKJKIKJLGLFLJLJLINFNGMININJOIOHNJOHOGPHPIOJPGPH"});
		tacticas.add(new Object[] {"7", "343", "AEAFAFAFAFBDBEBEBFBFCDCDCDCECEFBFCECEEFEFCFDFDGCGDHCGDGDGDGEJDIDIDIDIDAHAHAHAHAHAHAHAHAHAHBHCHBHCHBHDGDGDHDIDIEGEHEHEHEIFGFHFHFHFIHHHHHHHHHHBFBGBHBIBJCFCGCHCICJEEEFEHEJEKFEFFFHFJFKHEHFHHHJHKJEJFJHJJJKLHLHLHLHLHAJAJAJAJAKBJBJBKBKBLCKCKCLCLCLFKEKEMFMFNGLGMFLFLFMGKGLGLGLHMILILILILJLCBCCCDCECFDBDDDDECECFBFBFCGBGCIAIAIAIBICKBKDKBKCKCLBNBLCLDLDNBNDNDMDMEDFDGDHDIDJEGEHEHEHEIFGGGGHGIFIHEHFHHHJHKJDJFJHJJJLLELFLHLJLKMEMFNHMJMKEIEJEKEFEGGIGJGKGFGGIIJJJKJFIGKJKJKKKFKFMIMJMKMFMGNINJNJNFNGOIOIOIOGOGCJCKCLCMCNEMEMDLDLDNGMGNFMFNFNIMINIOIOIOKMKMKNKLKNLLLLLMNNLNMKMLNLNLNNECEDEEELEMGCGDGEGLGMJCJDJEJLJMKDKDKEKLKLMCMDMEMLMMNDNENFNKNLOFOGOGOIOJGFGGGHGIGJIFIGIHIIIJKFKGKHKIKJLGLGLHLILINFNGNHNINJOGOHOHOHOIPHPHPHPHPH"});
		tacticas.add(new Object[] {"8", "352", "AEAFAFAFAFBDBEBEBFBFCDCDCDCECEFBFCECEEFEFCFDFDGCGDHCGDGDGDGEJDIDIDIDIDAHAHAHAHAHAHAHAHAHAHBHCHBHCHBHDGDGDHDIDIEGEHEHEHEIFGFHFHFHFIHHHHHHHHHHBFBHBIBJBLDGDHDICJCKFGEHEIEKELGGGHGJGKGLIGIHHJHKHLKFJHJJJKJMLGLHLJLKLLAJAJAJAJAKBJBJBKBKBLCKCKCLCLCLFKEKEMFMFNGLGMFLFLFMGKGLGLGLHMILILILILJLCBCCCDCECFDBDDDDECECFBFBFCGBGCIAIAIAIBICKBKDKBKCKCLBNBLCLDLDNBNDNDMDMEBDBFBGBHBJCECFDGDHDIEDEEEGEHFIGDGEGFGHGIHDHEHFIHIIJCJEJFJHKJLDLELFLHLIDEDFCHDJDKEEFGEHFIEKHFHGHHHIHJJGJHJHJHJILFLGLHLILJMFMGMHMIMJNFNGNHNINJCJCKCLCMCNEMEMDLDLDNGMGNFMFNFNIMINIOIOIOKMKMKNKLKNLLLLLMNNLNMKMLNLNLNNECEEEFFGFIHCHEHFIFIHJCJDJEKGKHKDKELELFLGMDMENFNGNHOFOFOGOHOHPFPGPGPGPHFGFIFJEKEMIHIJIJHKHMKHKIKKJLJMLILJLKKKKLNHNINJMKMLOHOHOIOJOJPHPIPIPIPJ"});
		tacticas.add(new Object[] {"9", "424", "ABBCBDBDBECBCCCCCDCEDBDBDCEDEDFBFCECECFDGBGCGCHCGDIBICICIDHDJBJCJCICICAFAFAGAHAHBEBGAGAGAHBGBGBGCGCGCECFCGDGDHDDDEDFEHEIEEEFEFFFFGHFHFHFIGIGAHAHAIAJAJAHAIAIBIBKCICICIBIBIDHDIDICJCKEGEHEIDKDLFIFJFJEJEKIIIIIIHJHJBKBLBLBMANCKCLCMCMCNELELDMDNDNFLEMEMFMFNGLHMGMGMGNHLILIMIMINIMIMJMJMJNGBFCEDEEEFHBGBGCFDFEKBJBIBJCIDLAKAKBKCKDMALBLBMCMENANBMCMEMEOANCODOEOFBDBFAHBIBICDCECGCIDJFCFEFGFHFIHDGEGFGHHIHDHEHFIHIIJDJEJFJHJILDLELFLGMHBGBGBHBJBLDFCGCICKCLFGFHFIFKFMHGGHGJGKHLIGIHHJHKHLJGJHJJJKJLMHLILJLKLLEJEKELFMGNFKFLGMGNHNILJMINJNKNKLKMKNKOLOMKMMLNLNMOMKMKMMNNNOOJOKOLNMOOEEEFEHEJEKGDGEGHGKGLJEJFJHJJJKKEKGKHKIKKLEMFLHMJLKNFNGMHNINJNENFNHNJNKHFHGHHHIHJIFIGIHIIIJKFKGKHKIKJLGLGLHLILINFNGMHNINJOIOHNHOHOGPHPIPHPGPH"});
		tacticas.add(new Object[] {"10", "433", "ABBCBDBDCEDBCCCCCDCEEBEBECEDEDHBFCECECFDHBHCGCHCGDJBJCICIDHDKBKCKDICIBAFAFAHAHAHBEBGAGAGAHBGBGBGCGCGCEDICGDGDHDHDEDFDGDHEEEFEFEFEGHFHFHFHFHFAHAHAIAJAJAHAIBIBIBKCICICIBIBIDHCFDICJCKEEEHEIEJEKFIFJFJFJFKIIIIIIIIIICKBLBLBMANCKCLCMCMDNELELEMENENFLEMEMFMHNGLHMGMHMHNHLILIMJMJNIMIMKLKMKNDCDEDFDGEFGBECFCEDEEHBGBHBHCHDJBJAIBICJDKBKDKBKCKCLBNBLCLDLDNBNDNDNDMDCFBGBHBICJDFCFCHCJDJEEEFEHEJEKHEHFGHHJHKIEJFIHJJIKKEKFKHKJKKMFMGMHMIMJFJFKFLFMFNHIHJHKHLHMIIIJIKILIMKJKDKKKLKLMCMJMKMLMMNINJNJNKNLOIOIOIOJOKEJDIDJDKDLEKELFMEMGNHLHMHNGNHNJLIMINJOJNKMKMKNKLKNLLLLLMNNLNMLNLNLNLNNFBFCFDFEFFHCHDHEHFHGICIDIEIFIGKDKJKEKFKFMIMDMEMFMGNDNENFNFNGOEOFOGOGOGHFHGHHHIHJIFIGIHIIIJKFKGKHKIKJLGLGLHLILINFNGNHNINJOGOHOHOHOIPHPHPHPHPH"});
		tacticas.add(new Object[] {"11", "442", "ABBCBDBDCEDBCCCCCDCEEBEBECEDEDHBFCECECFDHBHCGCHCGDJBJCICIDHDKBKCKDICIBAFAFAHAHAJBEBGAGAGAHBGBGBGCGCGCECFCGDGDHDHDEDFDGDHEEEFEFEFEGHFHFHFHFHFAHAHAIAJAHAHAIBIBIBKCICICIBIBIDHDIDICJCKEEEHEIEJEKFIFJFJFJFKIIIIIIIIIICKBLBLBMANCKCLCMCMDNELELEMENENFLEMEMFMHNGLHMGMHMHNHLILIMJMJNINIMKLKMKNDDDEEEEEEFGBECFCEDEEIBGBHBHCHDJBJAIBICJDKBKDKBKCKCLBNBLCLDLDNBNDNDNDMDBFBHAGBHBJCFCFBHCJCJDEDFDHDJDKFEFFFHFJFKHEHFHHHJHKJEJGJHJIJKKELFLHLJKKEFEGDHEIEJEFEGEHEIEJFFGGGHGIFJIFIGHHIIIJKEKGJHKIKKLFLELHLKLJNINHNHNHNGEJEKEKDKDLEKELFMEMGNHLHMHNGNINJLIMINJOJNKMKMKNKLKNLLLLLMNNLNMLNLNLNLNNECEEEFFGFIHCHEHFIFIHJCJDJEKGKHKDKELELFLGMDMENFNGNHOFOFOGOHOHPFPGPGPGPHFGFIFJEKEMIHIJIJHKHMKHKIKKJLJMLILJLKKKKLNHNINJMKMLOHOHOIOJOJPHPIPIPIPJ"});
		tacticas.add(new Object[] {"12", "451", "ABBCBDBDCEDBCCCCCDCEDBDBDCEDEDHBFCECECFDHBHCGCHCGDJBJCICIDHDKBKCKDICICAFAFAHAHAHBEBGAGAGAHBGBGBGCGCGCECFCGDGDHDDDEDFEHEIEEEFEFFFFGHFHFHFIGIGAHAHAIAJAJAHAIBIBIBKCICICIBIBIDHDIDICJCKEGEHEIDKDLFIFJFJEJEKIIIIIIHJHJCKBLBLBMANCKCLCMCMDNELELDMDNDNFLEMEMFMHNGLHMGMHMHNHLILIMJMJNIMIMKLKMKNEBEDEEEEEFGBECFCEDEEIBGBHBHCHDKBJAIBICJDMALBKBKCKCNANBLCLDLDOANCMDNDMDBFBHAGBHBJCFCFBHCJCJDEDFEHDJDKFEFFFHFJFKHEHFHHHJHKJEJGJHJIJKLFLFLHLJLJDHDHCICJCKEGEHEJEKELFGFHGJGKGLIGIHJJJKJLKHKIKJKKKLLGLHLJLKLLNHNINJNJNKEJEKEKELENEKELFMEMGNHLHMHNGNINJLIMINJOKNKMKMKNLNMOLLLLLMNNNOMLNLMLNMOOCECFCGDHDHEDEEEFEHEIGDGEGFFHFIJDJEJFIHIIKDKEKFKGKHLDLELFLHLINENFNFNGNHHGHHHHHHHIIGIGIHIIIIKFKGKHKIKJLGLGLHLILIMGNGMHNIMINHNINHNGNHOHOHOHOHOH"});
		tacticas.add(new Object[] {"13", "523", "ABBCBEBEAFCABCBDBECEEBDBDBDDDDGAGBFBGCGCJAIBHBICIELAKBKCKDKEMALBLCLDLEAFAGAHAIAJAGAGAHAIAIBFBGBHBIBJEFEGDHEIEJGFGGGHGIGJIFIGIHIIIJKFKGKHKIKJAHAIAIAJBLBHBHBIBKCLCHCICJCKCLFIFIEJDKDLFIFIFJFKFLHIHJHKHLHMIIIJIKILIMAJBKBKBMANCKBKBLBMCODLDLDNDNENGMGMFNGNGOIKIMHNINJOKKKLKMKNLOLKLLLMLNMOFAEBDDDEDFGAFBFDFDFEJAIBICIDIEKAKAKCKDKEMCMBMDMEMFNDNENENFNFODOEOEOGOFBDAFAGAGAHCDBEBGBHBHCDCECFCGCHDDDEEFFGFGFDFEFFFGFGHCHDHEHFHGICIDIEIFIGCFCGBIBJBKDGDHDIDKDLFFFHFJFLFMHFHGHJHLHMJFJGJJJLJMLGLHLJLKLMNGNHNIMJMKDJDKDLENFOFKFLFLFNGOIKILIMINJOKKKLKMKOKOMJMKMLMNMMNJNJNKNKNLOJOIOKOKOLBEBFBGCICJDDDEDGDHDIFCFDFFFHFJHCHDHFHIHJJCJDJFJIJJLCLELFLHLIMEMFNGNHNIFEFGFHFIFKIEIGIHIIIKKEKFKHKJKKLFLGLHLILJNFNGNHNINJOGOGOHOIOIPHPGOHPIPH"});
		tacticas.add(new Object[] {"14", "532", "AEAFAFAFAFBDBEBEBFBFCDCDCDCECEFBFCECEEFEFCFDFDGCGDHCGDGDGDGEJDIDIDIDIDAHAHAHAHAHAHAHAHAHAHBHCHBHCHBHDGDGDHDIDIEGEHEHEHEIFGFHFHFHFIHHHHHHHHHHBFBHBIBJBLDGDHDICJCKFGEHEIEKELGGGHGJGKGLIGIHHJHKHLKFJHJJJKJMLGLHLJLKLLAJAJAJAJAKBJBJBKBKBLCKCKCLCLCLFKEKEMFMFNGLGMFLFLFMGKGLGLGLHMILILILILJLCBCCCDCECFDBDDDDECECFBFBFCGBGCIAIAIAIBICKBKDKBKCKCLBNBLCLDLDNBNDNDMDMEBDBFBGBHBJCECFDGDHDIEDEEEGEHFIGDGEGFGHGIHDHEHFIHIIJCJEJFJHKJLDLELFLHLIDEDFCHDJDKEEFGEHFIEKHFHGHHHIHJJGJHJHJHJILFLGLHLILJMFMGMHMIMJNFNGNHNINJCJCKCLCMCNEMEMDLDLDNGMGNFMFNFNIMINIOIOIOKMKMKNKLKNLLLLLMNNLNMKMLNLNLNNECEEEFFGFIHCHEHFIFIHJCJDJEKGKHKDKELELFLGMDMENFNGNHOFOFOGOHOHPFPGPGPGPHFGFIFJEKEMIHIJIJHKHMKHKIKKJLJMLILJLKKKKLNHNINJMKMLOHOHOIOJOJPHPIPIPIPJ"});
		tacticas.add(new Object[] {"15", "541", "ABBCBEBEAFCABCBDBECEEBDBDBDDDDGAGBFBGCGCJAIBHBICIELAKBKCKDKEMALBLCLDLEAFAGAHAIAJAGAGAHAIAIBFBGBHBIBJEFEGDHEIEJGFGGGHGIGJIFIGIHIIIJKFKGKHKIKJAHAIAIAJBLBHBHBIBKCLCHCICJCKCLFIFIEJDKDLFIFIFJFKFLHIHJHKHLHMIIIJIKILIMAJBKBKBMANCKBKBLBMCODLDLDNDNENGMGMFNGNGOIKIMHNINJOKKKLKMKNLOLKLLLMLNMODBDCDDDEDEFBECEDECFCHAGBGCGBHDJAJAJAJBJCMBMBLBKCKCOBNBNCMDMDNBNDNDNDNEBDAFAGAGAHCDBEBGBHBHCDCECFCGCHDDDEEFFGFGFDFEFFFGFGHCHDHEHFHGICIDIEIFIGCFBFBHBJCJDEDFDHDJDKFDFFFHFJFLGEGFHHGJGKIDJFJHJJILKDKELHKKKLMDMFNHMJMLDKDKDLDMDNFMEMELEMFNHLGNGMGNHOJMJNJOJOJOKMKMLNMNMNMLMLNMNNONNKNLNLNLNNCDCFCHCJCLFEFGFHFIFKIFHGHHHIIJJEJFJHJJJKLELGLHLILKNFMFNGMJNJOFOGPGOIOJFEFGFHFIFKIEIGIHIIIKKEKFKHKJKKLFLGLHLILJNGNHNHNHNIOHOGOIOIOHPHPIPIPGPH"});
		tacticas.add(new Object[] {"16", "Attack", "AEAFAFAFAFBDBEBEBFBFCDCDCDCECEFBFCECEEFEFCFDFDGCGDHCGDGDGDGEJDIDIDIDIDAHAHAHAHAHAHAHAHAHAHBHCHBHCHBHDGDGDHDIDIEGEHEHEHEIFGFHFHFHFIHHHHHHHHHHBDBFBGBHBJCECFDGDHDIECEEEGEHFIGDGEGFGHGIHDHEHFIHIIKCKEJFJHJJMDMELFLHLIAJAJAJAJAKBJBJBKBKBLCKCKCLCLCLFKEKEMFMFNGLGMFLFLFMGKGLGLGLHMILILILILJLEAEBECEEEFHAHBGCGCGDKAJBIBJBJCLAKAKBKBLCMDMCMBMCMDNBNBNDNENFNBODNEOEOFBFBHBIBJBLDGDHDICJCKFGEHEIEKEMGGGHGJGKGLIGIHHJHKHLJFJHJJKKKMLGLHMJMKMLDEDFDHDJDKFEFGFHFIFKIFIGHHIIIJKFKGJHKIKJLFLGLHLILJMFNGNHNIMJNGNGOHNINIEJEKEMENEOGLGMGMHNHOJMJNINJNKOLMKNKNKOLOMLMMMNMMMLNJNKNLNNNNOJOKNKOLNNGCFEFFGGGIICIEHFJGJHKCKDJFLGLHMDMELFLFLGNENFNGNGOHOFOFPGPHOHPFPGPGPGPHGGGIGJFKGMJHJIIJIKIMLHLIKJKLKMLILJMJMKMLOHNIOINJNKOHPHPIOJOJPHPIPIPIPJ"});
		tacticas.add(new Object[] {"17", "Defend", "ADBFAGBFAGBDBEBEBEBFCDCECECEBFDDDEDEDECFFDFEFEFEFEFDFDFDFDFDHDHDHDHDHDAGAHAHAGAHAFAGAGAGAHBFBGBGBGAHCFCGCGCGCHEFEGEGEGEGEGEGEGEGEGGGGGGGGGGGAHAIBHAHAIAHAIAIAIAJAHBIBIBIBJCHCICICICJEIEIEIEIEJEIEIEIEIEIGIGIGIGIGIAIBJAIBJALBJBKBKBKBLBJCKCKCKCLCJDKDKDKDLFKFKFKFKFLFLFLFLFLFLHLHLHLHLHLBCBDBDBDBDCBCCCCCCCDDBDCDCDCCDEBECECECDDGBGCGCGCGCHBHBHBHBHBJBJBJBJBJBBFAGBGBGBGBEBFCGCHCIECEEEFEGEHFCFEFFFGFGHDHEHFHGHHIDIEIFJGJHKEKEKFLGMHBIBIBIAIBJCGCHCIBJBKEHEIEJEKEMFIFIFJFKFMHHHIHJHKHLJHJIIJIKILMHLIKJKKKKBLBLBLBLBMCLCMCMCMCNCLDMDMDMDNDLEMEMEMENGMGMGMGMGNHNHNHNHNHNJNJNJNJNJNCGCHCHCHCIEDEFEHEJELGDGGGHGIGLIEIFIHIJIKJDJFJHJJJLLBLELHLKLNNBNEMHNKNNHGHHHHHHHIIFIGIHIIIJKFKGKHKIKJLGLGLHLILIMFMGMHMIMJOHOGNHOIOHPHPGOHPIPH"});
		tacticas.add(new Object[] {"18", "Sweep", "ABBCBDBDCEDBCCCCCDCEEBEBECEDEDGBFCECECFDFBFCFCFCFDGBGCGCGDGDHCHCHCHCHCAFAFAHAHAJBEBGAGAGAHBGBGBGCGCGDHCFCGDGDHFFEGEGEHFJIGHGHHHIIIKEKFKGKIKKAHAHAIAJAHAHAIBIBIBKCICICIBIBICEDIDICJCKDGDHDIDIDIEHEHEHEHEHGHGHGHGHGHCKBLBLBMANCKCLCMCMDNELELEMENENFLEMEMFMGNFLFMFMFMFNGLGLGMGMGNHMHMHMHMHMDDDEEEEEEFGBECFCEDEEIBGBHBHCHDJBJAIBICJDJBKDKBKCKCLBNBLCLDLDNBNDNDNDMDBFBHAGBHBJCFCFBHCJCJDEDFDHDJDKFEFFFHFJFKHEHFHHHJHKJEJGJHJIJKLGLHLHLHLIEFEGDHEIEJEFEGEHEIEJFFGGGHGIFJIFIGHHIIIJJEKGJHKIJKLFLELHLKLJNINHNHNHNGEJEKEKDKDLEKELFMEMGNHLHMHNGNINJLIMINJOJNKMKMKNKLJNLLLLLMNNLNMLNLNLNLNNECEEEFFGFIHCHEHFIFIHJCJDJEKGKHKDKELELFLGMDMENFNGNHOFOFOGOHOHPFPGPGPGPHFGFIFJEKEMIHIJIJHKHMKHKIKKJLJMLILJLKKKKLNHNINJMKMLOHOHOIOJOJPHPIPIPIPJ"});
		
		return tacticas;
	}
	
	private List<Object[]> get_tacticas(WebClient navegador, Integer team_id) throws FailingHttpStatusCodeException, MalformedURLException, IOException {
		HtmlPage pagina = navegador.getPage(AsistenteBO.SOKKER_URL + "/tactedit/teamID/" + (team_id == null ? "" : team_id));

		List<HtmlAnchor> htmlTacticas = (List<HtmlAnchor>)pagina.getByXPath("//div[@class='panel-body']//a[contains(@href,'teamID') and contains(@href,'tactedit')]");
		List<Object[]> tacticas = new ArrayList<Object[]>();

		for (HtmlAnchor t : htmlTacticas) {
			String href = t.getAttributes().getNamedItem("href").getNodeValue();
			Integer id = Integer.valueOf(href.substring(href.indexOf("tactID") + 7, href.indexOf("#")));
			HtmlPage paginaTactica = navegador.getPage(AsistenteBO.SOKKER_URL + "/read_tact.php?id=" + id);
			String tactica = paginaTactica.asText().split("&")[0].split("=")[1];

			if (id > 18) {
				tacticas.add(new Object[]{id, t.asText(), tactica});
			}
		}
		
		return tacticas;
	}
	
	public Integer obtener_tid_NT(WebClient navegador) throws FailingHttpStatusCodeException, MalformedURLException, IOException {
		Object document = JSONUtil.getJson(navegador, AsistenteBO.SOKKER_URL + "/api/current");
		LinkedHashMap<String, Object> datos = JsonPath.read(document, "$");

		int tid_nt = JSONUtil.getInteger(datos, "nationalTeamId");
		return tid_nt == 0 ? null : tid_nt;
	}
}
