plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android' version '1.8.22' // Si usas Kotlin
}

android {
    namespace "com.formulamanager.sokker.asistente"
    compileSdk 36

    defaultConfig {
        applicationId "com.formulamanager.sokker.asistente"
        minSdk 21
        targetSdk 36
        versionCode 11
        versionName "1.11"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = "1.8"
    }
}

dependencies {
    implementation platform("org.jetbrains.kotlin:kotlin-bom:1.8.22")
    implementation "org.jetbrains.kotlin:kotlin-stdlib"
    implementation "androidx.appcompat:appcompat:1.7.1"
    implementation "androidx.constraintlayout:constraintlayout:2.2.1"
    testImplementation "junit:junit:4.13.2"
    androidTestImplementation "androidx.test.ext:junit:1.2.1"
    androidTestImplementation "androidx.test.espresso:espresso-core:3.6.1"
}